### 버전 정보
[versions]
compileSdk = "34"
targetSdk = "34"
minSdk = "24"

# AndroidX Compose Versions
androidx-compose-bom = "2024.02.00"

# Core AndroidX Versions
androidx-core-ktx = "1.12.0"
androidx-lifecycle-runtime-ktx = "2.7.0"
androidx-activity-compose = "1.8.2"
androidx-navigation-compose = "2.7.7"

# Coroutines
coroutines = "1.7.3"

# Networking Libraries Versions
okhttp3 = "4.12.0"
retrofit2 = "2.9.0"
retrofit2-converter-gson = "2.9.0"
retrofit2-jackson = "2.3.0"
okhttp3-logging-interceptor = "4.9.3"

# Dependency Injection (Hilt) Versions
dagger-hilt = "2.45"
dagger-hilt-compiler = "2.45"

# Testing Libraries Versions
test-junit = "4.13.2"
android-test-androidx-ext-junit = "1.1.5"
android-test-androidx-espresso-core = "3.5.1"
android-test-androidx-compose-bom = "2024.02.00"

########################################################################
########################################################################
########################################################################

### 라이브러리
[libraries]

# AndroidX Compose Libraries
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preivew = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Networking Libraries
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2-converter-gson" }
retrofit2-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit2-jackson" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3-logging-interceptor" }

# Dependency Injection (Hilt) Libraries
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt-compiler" }

# Testing Libraries
test-junit = { module = "junit:junit", version.ref = "test-junit" }
android-test-androidx-ext-junit = { module = "androidx.test.ext:junit", version.ref = "android-test-androidx-ext-junit" }
android-test-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "android-test-androidx-espresso-core" }
android-test-androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "android-test-androidx-compose-bom" }

# Debug libraries
debug-androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }